### PR TITLE
[0.1] Fix ExportVCF issue with info field + semicolons

### LINKED ISSUE #1098: exportvcf sometimes adding a semi-colon at the end of the INFO field

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #1098

### CODE REVIEW

File: src/test/scala/is/hail/io/ExportVcfSuite.scala [hunk 1]
```diff
@@ -167,4 +167,21 @@ class ExportVcfSuite extends SparkSuite {
         .exportVCF(out)
     }
   }
+
+  @Test def testInfoFieldSemicolons() {
+    val vds = hc.importVCF("src/test/resources/sample.vcf", dropSamples = true)
+      .annotateVariantsExpr("va.info = {foo: 5, bar: NA: Int}")
+
+    val out = tmpDir.createLocalTempFile("foo", "vcf")
+    //    val out = "/tmp/out.vcf"
```
Comment (jigold) [inline src/test/scala/is/hail/io/ExportVcfSuite.scala]: delete
