### PR TITLE
Fix TextTableReader delim problem

### LINKED ISSUE #2581: Using '|' as delimiter on import_table causes inifinite loop and OOM
Easily replicable. I will have a fix soon.

### PR DESCRIPTION
**Pull request by tpoterba**
fixes #2581

### CODE REVIEW

**Comment by tpoterba** [comment]
Assigning @cseed because I want to better understand the tradeoffs of making `def sepChar` a `Function` object. Is this an OK thing to do here?

File: src/main/scala/is/hail/utils/TextTableReader.scala [hunk 1]
```diff
@@ -13,15 +13,23 @@ import org.apache.spark.sql.Row
...
+    val matchSep: Int => Int = separator.length match {
+      case 0 => fatal("Hail does not currently support 0-character separators")
+      case 1 =>
+        val sepChar = separator(0)
+        (i: Int) => if (s(i) == sepChar) 1 else -1
+      case _ =>
+        val p = Pattern.compile(separator)
+        val m = p.matcher(s)
+
+      { (i: Int) =>
```
Comment (cseed) [inline src/main/scala/is/hail/utils/TextTableReader.scala]: Indentation seems wrong?  Sometimes I find IntelliJ gets confused when  { starts a line.  You might try putting the { after the =>.

File: src/main/scala/is/hail/utils/TextTableReader.scala [hunk 2]
```diff
@@ -13,15 +13,23 @@ import org.apache.spark.sql.Row
...
-    val p = Pattern.compile(separator)
-    val m = p.matcher(s)
 
-    def matchSep(i: Int): Int = {
-      m.region(i, s.length)
-      if (m.lookingAt())
-        m.end() - m.start()
-      else
-        -1
+    val matchSep: Int => Int = separator.length match {
```
Comment (cseed) [inline src/main/scala/is/hail/utils/TextTableReader.scala]: I think this will probably be a wash but if you're concerned benchmark it.

File: python/hail/api1/context.py [hunk 3]
```diff
@@ -467,8 +467,9 @@ def import_table(self, paths, key=[], min_partitions=None, impute=False, no_head
         information about possible field types. While this is a bit slower for large files, (the 
         file is parsed twice), the convenience is often worth this cost.
         
-        The ``delimiter`` parameter is a field separator regex. This regex follows the 
-         `Java regex standard <http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html>`_.
+        The ``delimiter`` parameter is either a delimiter character (if a single character) or a field separator
+        regex (2 or more characters). This regex follows the `Java regex standard
```
Comment (cseed) [inline python/hail/api1/context.py]: I personally don't like changing the interpretation on the length but I understand the argument for conciseness and python compatibility.  I'd probably argue for separate `delimiter_char` and `delimiter_regex` arguments.  No need to change anything, I just wanted the comment on the record.

Comment (tpoterba) [reply python/hail/api1/context.py]: Yeah, but I don't totally like splitting it out into delim_char and delim_regex either.

Maybe something like `regex={True, False, 'auto'}` (auto is this behavior, and default)?

Comment (cseed) [reply python/hail/api1/context.py]: Sigh, I don't really like that either, the interpreting delimiter is non-local.  I say we stick with your current change.

**Comment by cseed** [comment]
You should PR this to 0.2, too.

**Comment by tpoterba** [comment]
to 0.1, you mean? That's an interface change :|

**Comment by tpoterba** [comment]
eh, could be just written off as a bugfix. I'll do that.
