### PR TITLE
[hail] move head/tail from crdd to rvd; fix linear memory usage

### LINKED ISSUE #7765: Fix memory usage in ContextRDD.head/tail
Move the partition counts calculation to RVD

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #7765

### CODE REVIEW

File: hail/src/main/scala/is/hail/rvd/RVD.scala [hunk 1]
```diff
@@ -469,7 +493,29 @@ class RVD(
...
+        val PCSubsetOffset(idx, _, nDrop) =
+          incrementalPCSubsetOffset(n, Range.inclusive(getNumPartitions - 1, 0, -1))(
+            crddBoundary.runJob(getIteratorSize, _)
+          )
+        idx -> nDrop
+    }
+
+    val newRDD = crdd.mapPartitionsWithIndex({ case (i, it) =>
+      if (i == idxFirst)
+        it.drop(nDrop.toInt)
```
Comment (catoverdrive) [inline hail/src/main/scala/is/hail/rvd/RVD.scala]: I *believe* `it.drop` is going to have issues with region clearing, since by default it's just going to call `next()` and `hasNext()` on the iterator.

Comment (tpoterba) [reply hail/src/main/scala/is/hail/rvd/RVD.scala]: ack, good point.
