### PR TITLE
Fix the If unification problem

### LINKED ISSUE #4134: handle missingness correctly for arrays in user interface
Example that currently fails:

```
>>> mt = hl.import_vcf('sample.vcf')
>>> mt.annotate_entries(PL = hl.cond(mt.DP > 20, mt.PL, hl.map(lambda x: x, mt.PL)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cotton/hail/python/hail/matrixtable.py", line 975, in annotate_entries
    return self._select_entries(caller, s=self.entry.annotate(**e))
  File "/home/cotton/hail/python/hail/typecheck/check.py", line 547, in wrapper
    return f(*args_, **kwargs_)
  File "/home/cotton/hail/python/hail/matrixtable.py", line 2887, in _select_entries
    return cleanup(MatrixTable(base._jvds.selectEntries(str(s._ir))))
  File "/home/cotton/opt/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/home/cotton/hail/python/hail/utils/java.py", line 212, in deco
    'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
hail.utils.java.FatalError: AssertionError: assertion failed: mismatch:
  array<int32>
  array<int32>
  ApplyComparisonOp(GT(int32,int32),GetField(ArrayRef(GetField(Ref(va,struct{locus: locus<GRCh37>, alleles: array<str>, rsid: str, qual: float64, filters: set<str>, info: struct{NEGATIVE_TRAIN_SITE: bool, HWP: float64, AC: array<int32>, culprit: str, MQ0: int32, ReadPosRankSum: float64, AN: int32, InbreedingCoeff: float64, AF: array<float64>, GQ_STDDEV: float64, FS: float64, DP: int32, GQ_MEAN: float64, POSITIVE_TRAIN_SITE: bool, VQSLOD: float64, ClippingRankSum: float64, BaseQRankSum: float64, MLEAF: array<float64>, MLEAC: array<int32>, MQ: float64, QD: float64, END: int32, DB: bool, HaplotypeScore: float64, MQRankSum: float64, CCC: int32, NCC: int32, DS: bool}, `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`: array<struct{GT: call, AD: array<int32>, DP: int32, GQ: int32, PL: array<int32>}>}),the entries! [877f12a8827e18f61222c6c8c5fb04a8]),Ref(i,int32)),DP),I32(20))

Java stack trace:
java.lang.AssertionError: assertion failed: mismatch:
  array<int32>
  array<int32>
  ApplyComparisonOp(GT(int32,int32),GetField(ArrayRef(GetField(Ref(va,struct{locus: locus<GRCh37>, alleles: array<str>, rsid: str, qual: float64, filters: set<str>, info: struct{NEGATIVE_TRAIN_SITE: bool, HWP: float64, AC: array<int32>, culprit: str, MQ0: int32, ReadPosRankSum: float64, AN: int32, InbreedingCoeff: float64, AF: array<float64>, GQ_STDDEV: float64, FS: float64, DP: int32, GQ_MEAN: float64, POSITIVE_TRAIN_SITE: bool, VQSLOD: float64, ClippingRankSum: float64, BaseQRankSum: float64, MLEAF: array<float64>, MLEAC: array<int32>, MQ: float64, QD: float64, END: int32, DB: bool, HaplotypeScore: float64, MQRankSum: float64, CCC: int32, NCC: int32, DS: bool}, `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`: array<struct{GT: call, AD: array<int32>, DP: int32, GQ: int32, PL: array<int32>}>}),the entries! [877f12a8827e18f61222c6c8c5fb04a8]),Ref(i,int32)),DP),I32(20))
	at scala.Predef$.assert(Predef.scala:170)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:10)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.If.typ(IR.scala:77)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:63)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:59)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:59)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.InsertFields.typ(IR.scala:154)
	at is.hail.expr.ir.InsertFields.typ(IR.scala:153)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:39)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.ArrayMap.typ(IR.scala:101)
	at is.hail.expr.ir.ArrayMap.typ(IR.scala:100)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:63)
	at is.hail.expr.ir.Infer$$anonfun$apply$5.apply(Infer.scala:59)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at is.hail.expr.ir.Infer$.apply(Infer.scala:59)
	at is.hail.expr.ir.InferIR$class.typ(IR.scala:58)
	at is.hail.expr.ir.InsertFields.typ(IR.scala:154)
	at is.hail.expr.ir.MatrixMapEntries.<init>(MatrixIR.scala:1075)
	at is.hail.variant.MatrixTable.selectEntries(MatrixTable.scala:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

Hail version: devel-0eb009391fd5
Error summary: AssertionError: assertion failed: mismatch:
  array<int32>
  array<int32>
  ApplyComparisonOp(GT(int32,int32),GetField(ArrayRef(GetField(Ref(va,struct{locus: locus<GRCh37>, alleles: array<str>, rsid: str, qual: float64, filters: set<str>, info: struct{NEGATIVE_TRAIN_SITE: bool, HWP: float64, AC: array<int32>, culprit: str, MQ0: int32, ReadPosRankSum: float64, AN: int32, InbreedingCoeff: float64, AF: array<float64>, GQ_STDDEV: float64, FS: float64, DP: int32, GQ_MEAN: float64, POSITIVE_TRAIN_SITE: bool, VQSLOD: float64, ClippingRankSum: float64, BaseQRankSum: float64, MLEAF: array<float64>, MLEAC: array<int32>, MQ: float64, QD: float64, END: int32, DB: bool, HaplotypeScore: float64, MQRankSum: float64, CCC: int32, NCC: int32, DS: bool}, `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`: array<struct{GT: call, AD: array<int32>, DP: int32, GQ: int32, PL: array<int32>}>}),the entries! [877f12a8827e18f61222c6c8c5fb04a8]),Ref(i,int32)),DP),I32(20))
```

### PR DESCRIPTION
**Pull request by tpoterba**
The fix is somewhat subtle and relies on PruneDeadFields, which is called (a) by the optimizer and (b) by the compiler, so this is safe. The important piece is that the process of upcasting strips requiredness.

This isn't a great design, but I'm comfortable with it for now since I hope physical types will solve this in The Right Way™ before 0.2 release anyway.

fixes #4134

### CODE REVIEW

**Comment by tpoterba** [comment]
cc @cseed

File: src/main/scala/is/hail/expr/ir/Infer.scala [hunk 1]
```diff
@@ -7,9 +7,10 @@ object Infer {
     ir match {
       case If(cond, cnsq, altr) =>
         assert(cond.typ.isOfType(TBoolean()))
-        assert(cnsq.typ == altr.typ, s"mismatch:\n  ${ cnsq.typ.parsableString() }\n  ${ altr.typ.parsableString() }\n  $cond")
-        cnsq.typ
-
+        if (cnsq.typ != altr.typ)
```
Comment (catoverdrive) [inline src/main/scala/is/hail/expr/ir/Infer.scala]: can you keep an assert here? `cnsq.typ isOfType altr.typ` or something

File: src/main/scala/is/hail/expr/ir/TypeCheck.scala [hunk 2]
```diff
@@ -5,16 +5,25 @@ import is.hail.utils._
 
 object TypeCheck {
   def apply(ir: IR, aggEnv: Option[Env[Type]] = None) {
+    apply(ir, new Env[Type](), aggEnv)
```
Comment (catoverdrive) [inline src/main/scala/is/hail/expr/ir/TypeCheck.scala]: there's nothing in the `try` block, and the `apply` call should catch/throw the right exception, so I think the try/catch thing can go away here?

File: src/test/scala/is/hail/expr/ir/IRSuite.scala [hunk 3]
```diff
@@ -136,6 +136,19 @@ class IRSuite extends SparkSuite {
     assertEvalsTo(If(True(), NA(TInt32()), I32(7)), null)
   }
 
+  @Test def testIfWithDifferentRequiredness() {
+    val t = TStruct("foo" -> TArray(TInt32Required, required = true))
+    val value = Row(FastIndexedSeq(1, 2, 3))
+    assertEvalsTo(
```
Comment (catoverdrive) [inline src/test/scala/is/hail/expr/ir/IRSuite.scala]: assertEvalsTo checks the non-optimized evaluation too, right? Otherwise this gets optimized away.

File: src/main/scala/is/hail/expr/ir/PruneDeadFields.scala [hunk 4]
```diff
@@ -1006,8 +1006,9 @@ object PruneDeadFields {
         case ta: TArray =>
           val ra = rType.asInstanceOf[TArray]
           val uid = genUID()
-          val ref = Ref(uid, ta.elementType)
+          val ref = Ref(uid, -ta.elementType)
```
Comment (catoverdrive) [inline src/main/scala/is/hail/expr/ir/PruneDeadFields.scala]: could `ra` ever have a required element type?

File: src/main/scala/is/hail/expr/ir/Infer.scala [hunk 5]
```diff
@@ -7,9 +7,10 @@ object Infer {
...
+          cnsq.typ.deepOptional()
```
Comment (cseed) [inline src/main/scala/is/hail/expr/ir/Infer.scala]: Can we keep the assert that `cnsq.typ.deepOption() == altr.typ.deepOptional()`?

File: src/main/scala/is/hail/expr/ir/TypeCheck.scala [hunk 6]
```diff
@@ -5,16 +5,25 @@ import is.hail.utils._
...
     try {
-      apply(ir, new Env[Type](), aggEnv)
```
Comment (cseed) [inline src/main/scala/is/hail/expr/ir/TypeCheck.scala]: The try is empty now?

File: src/test/scala/is/hail/expr/ir/IRSuite.scala [hunk 7]
```diff
@@ -136,6 +136,19 @@ class IRSuite extends SparkSuite {
     assertEvalsTo(If(True(), NA(TInt32()), I32(7)), null)
   }
 
+  @Test def testIfWithDifferentRequiredness() {
```
Comment (cseed) [inline src/test/scala/is/hail/expr/ir/IRSuite.scala]: Can we also test arrays?

File: src/test/scala/is/hail/expr/ir/IRSuite.scala (hunk 3 above)
Comment (catoverdrive) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: well, I guess it doesn't actually check the non-optimized evaluation (for compiled functions, which is where the region offset problem would come up). But as long as the PruneDeadFields step comes after the simplify it wouldn't get optimized away anyways, right?

File: src/main/scala/is/hail/expr/ir/Infer.scala (hunk 1 above)
Comment (tpoterba) [reply src/main/scala/is/hail/expr/ir/Infer.scala]: yes, that seems like an absolute requirement. good call.

File: src/main/scala/is/hail/expr/ir/TypeCheck.scala (hunk 2 above)
Comment (tpoterba) [reply src/main/scala/is/hail/expr/ir/TypeCheck.scala]: oops, I totally meant to delete that.

File: src/test/scala/is/hail/expr/ir/IRSuite.scala (hunk 3 above)
Comment (tpoterba) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: correct. I can change the condition if you want, to something that evaluates a random number?

Comment (catoverdrive) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: Sure, that works. I will sometimes do something like `ArrayLen(GetField(In(0, t), "foo")).ceq(3)` or something that's pretty obviously true but statically non-optimizable, but I think this is probably also fine until physical types go in and we change the simplify rules back again?

File: src/main/scala/is/hail/expr/ir/PruneDeadFields.scala (hunk 4 above)
Comment (tpoterba) [reply src/main/scala/is/hail/expr/ir/PruneDeadFields.scala]: Not given our current system. It would totally be possible for somebody to introduce requiredness in a way that breaks this, but we only use requiredness for PLs and dosages right now.

File: src/main/scala/is/hail/expr/ir/Infer.scala (hunk 5 above)
Comment (tpoterba) [reply src/main/scala/is/hail/expr/ir/Infer.scala]: added isOfType check.

File: src/test/scala/is/hail/expr/ir/IRSuite.scala (hunk 7 above)
Comment (tpoterba) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: I think this is testing arrays.

I also tested the python code that triggered the crash in the issue, which worked.

I can add that as a python test, but this test does isolate the behavior

File: src/test/scala/is/hail/expr/ir/IRSuite.scala (hunk 3 above)
Comment (tpoterba) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: oh, awesome. I just changed it to an `In` bool

Comment (tpoterba) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: that makes way more sense.

File: src/test/scala/is/hail/expr/ir/IRSuite.scala (hunk 7 above)
Comment (cseed) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: Oops, you're totally right.  Can we also test structs?  :-)

Comment (tpoterba) [reply src/test/scala/is/hail/expr/ir/IRSuite.scala]: ah, yeah.

**Comment by tpoterba** [comment]
added a struct test.
