### PR TITLE
[hail][bugfix] Fix TableHead prune behavior w.r.t keys

### LINKED ISSUE #7317: [hail] wrong result from combination of key by and head
The reversal of the table should mean that the first 10 entries are -999_999, -999_998, etc. but instead it's just reversing the head of the table.
```
In [3]:     t = hl.utils.range_table(1_000_000, n_partitions=100) 
   ...:     t = t.key_by(rev_idx=-t.idx) 
   ...:     t.take(10)                                                                                                                                                                                                                                                          
Out[3]: 
[Struct(idx=9, rev_idx=-9),
 Struct(idx=8, rev_idx=-8),
 Struct(idx=7, rev_idx=-7),
 Struct(idx=6, rev_idx=-6),
 Struct(idx=5, rev_idx=-5),
 Struct(idx=4, rev_idx=-4),
 Struct(idx=3, rev_idx=-3),
 Struct(idx=2, rev_idx=-2),
 Struct(idx=1, rev_idx=-1),
 Struct(idx=0, rev_idx=0)]
```

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #7317

### CODE REVIEW

File: hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala [hunk 1]
```diff
@@ -698,6 +698,14 @@ class PruneSuite extends HailSuite {
       Array(subsetTable(tab.typ, "row.3", "global.g2")))
   }
 
+  @Test def testTableHeadMemo() {
+    checkMemo(
+      TableHead(tab, 10L),
+      subsetTable(tab.typ.copy(key = FastIndexedSeq()), "global.g1"),
+      Array(subsetTable(tab.typ, "row.3", "global.g1")))
+
```
Comment (danking) [inline hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala]: blank line
```suggestion

```
