### PR TITLE
fix IR range for start < stop; add some more tests

### LINKED ISSUE #3648: hl.range behaves incorrectly when end before start
hl.range behaves incorrectly when end is after start.  For example:

```
>>> hl.range(-9, -10, 3).value
[-9]
```

The cases considered by `testArrayRange` should be expanded.  (end <= start, negative step, step bigger than difference between start and end.)

### PR DESCRIPTION
**Pull request by catoverdrive**
Fixes #3648.

### CODE REVIEW

File: src/test/scala/is/hail/expr/ir/CompileSuite.scala [hunk 1]
```diff
@@ -424,6 +426,8 @@ class CompileSuite {
     val aoff = f(region, start, false, stop, false, step, false)
     val actual = new UnsafeIndexedSeq(tRange, region, aoff)
     assert(actual.sameElements(expected))
+
+    TestUtils.interceptFatal("step size"){ f(region, 1, false, 5, false, 0, false) }
```
Comment (cseed) [inline src/test/scala/is/hail/expr/ir/CompileSuite.scala]: CompileSuite is out, IRSuite (and friends) are in.  Move these testArrayRange tests to IRSuite.  @patrick-schultz has handy utility functions for checking exceptions.  If those aren't in yet, maybe he can PR them independently?

File: src/test/scala/is/hail/expr/ir/IRSuite.scala [hunk 2]
```diff
@@ -120,4 +121,17 @@ class IRSuite extends TestNGSuite {
     assertEvalsTo(ArrayFilter(a, "x",
       ApplyComparisonOp(LT(TInt32()), Ref("x", TInt32()), I32(6))), FastIndexedSeq(3))
   }
+
+  @Test def testArrayRange() {
+    val range = { (start: Int, stop: Int, step: Int) => ArrayRange(I32(start), I32(stop), I32(step)) }
```
Comment (cseed) [inline src/test/scala/is/hail/expr/ir/IRSuite.scala]: def is clearer?

I also I increasingly think we need an IR interface layer that removes some of the biolerplate and makes simple examples easier to write.

File: src/test/scala/is/hail/expr/ir/IRSuite.scala [hunk 3]
```diff
@@ -120,4 +121,17 @@ class IRSuite extends TestNGSuite {
...
+
+    assertEvalsTo(range(-9, -10, 2), FastIndexedSeq())
+    assertEvalsTo(range(-9, -10, 3), FastIndexedSeq())
+    assertEvalsTo(range(1, 5, -2), FastIndexedSeq())
+    assertEvalsTo(range(5, 1, -2), FastIndexedSeq(5, 3))
```
Comment (cseed) [inline src/test/scala/is/hail/expr/ir/IRSuite.scala]: You should just expand the cases in the testArrayRange bit where you loop over values for start, stop and step.

File: src/test/scala/is/hail/expr/ir/CompileSuite.scala (hunk 1 above)
Comment (catoverdrive) [reply src/test/scala/is/hail/expr/ir/CompileSuite.scala]: I addressed all the other comments (including moving the tests above this test into InterpretSuite), but I've left this part in here for now because all the `eval` stuff does the `Interpret` and so would throw an error before checking the compiler. I can move when Patrick's stuff goes in?

Comment (catoverdrive) [reply src/test/scala/is/hail/expr/ir/CompileSuite.scala]: (ok, fixed with the new stuff).

File: src/main/scala/is/hail/expr/ir/Interpret.scala [hunk 4]
```diff
@@ -193,6 +193,8 @@ object Interpret {
         val startValue = interpret(start, env, args, agg)
         val stopValue = interpret(stop, env, args, agg)
         val stepValue = interpret(step, env, args, agg)
+        if (stepValue == 0)
+          fatal("Array range cannot have step size 0.")
```
Comment (cseed) [inline src/main/scala/is/hail/expr/ir/Interpret.scala]: Good, caught another one.
