### PR TITLE
Fix Genotype from linear function

### LINKED ISSUE #714: Odd importbgen output
We tried loading a large bgen file (chr21 - 950k Variants, 150k samples) from UK Biobank. It seemed to proceed ok and generate a VDS file that was loadable, but upon looking at variantqc, it appears that at the large majority of sites, all homref calls are missing. There were no 'tolerance too low' messages while loading, and this property seems to be retained across several runs with difference tolerances.

### PR DESCRIPTION
**Pull request by tpoterba**
Fix bug in Genotype.gtFromLinear

We had a destructive bug in this function that
caused dosages to never result in a HomRef call.
Our tests were inadequate because we used this
function both in the generator and import, i.e.
testing it against itself.  I added a unit test for
this method.

Fixes #714

### CODE REVIEW

File: src/test/scala/org/broadinstitute/hail/variant/GenotypeSuite.scala [hunk 1]
```diff
@@ -103,15 +104,39 @@ class GenotypeSuite extends TestNGSuite {
...
+  @Test def gtPairAndGtPairSqrtEqual() {
+    forAll(Gen.choose(0, 10000)) { (idx) =>
       Genotype.gtPair(idx) == Genotype.gtPairSqrt(idx)
     }.check()
   }
+
+  @Test def testGtFromLinear() {
+    val gen = for (nGenotype <- Gen.choose(2, 10).map(triangleNumberOf);
+      dosageGen = Gen.partition(nGenotype, 32768);
+      results <- Gen.buildableOfN[Array, Array[Int]](10000, dosageGen)) yield results
```
Comment (cseed) [inline src/test/scala/org/broadinstitute/hail/variant/GenotypeSuite.scala]: This is unnecessarily complicated.  Don't generate an array of dosages and then check properties on them independently.

File: src/test/scala/org/broadinstitute/hail/io/LoadBgenSuite.scala [hunk 2]
```diff
@@ -101,7 +104,6 @@ class LoadBgenSuite extends SparkSuite {
         hadoopDelete(qcToolLogFile, sc.hadoopConfiguration, recursive = true)
 
         var s = State(sc, sqlContext, vds)
-        s = SplitMulti.run(s, Array[String]())
         s = RenameSamples.run(s, Array("-i", sampleRenameFile))
```
Comment (cseed) [inline src/test/scala/org/broadinstitute/hail/io/LoadBgenSuite.scala]: Once you filter samples on "NA", you can get rid of the `RenameSamples`.

File: src/main/scala/org/broadinstitute/hail/check/Gen.scala [hunk 3]
```diff
@@ -43,8 +43,19 @@ object Gen {
...
+    val allOneBucket = Gen { p =>
+      val a = Array.fill[Int](parts)(0)
+      a(p.rng.nextInt(0, parts - 1)) = sum
+      a
+    }
+
+    Gen.frequency(1 -> allOneBucket, 9 -> Gen { p => partition(p.rng, sum, parts) })
+  }
+
+  def partition(parts: Int): Gen[Array[Int]] = Gen { p => partition(p.rng, p.size, parts) }
```
Comment (cseed) [inline src/main/scala/org/broadinstitute/hail/check/Gen.scala]: This is a confusing operation.  You might rename it `partitionSize`.

**Comment by cseed** [comment]
Back to you.

File: src/test/scala/org/broadinstitute/hail/variant/GenotypeSuite.scala (hunk 1 above)
Comment (tpoterba) [inline src/test/scala/org/broadinstitute/hail/variant/GenotypeSuite.scala]: I want to check more than 10, though.  How can we do that?  Maybe introduce a multiplier for small things?

**Comment by tpoterba** [comment]
Back to you.

File: src/test/scala/org/broadinstitute/hail/variant/GenotypeSuite.scala (hunk 1 above)
Comment (cseed) [inline src/test/scala/org/broadinstitute/hail/variant/GenotypeSuite.scala]: Dan's idea was to have a notion of "total size" available for all runs of a gen, and then run small gens more since they use up more size.  I think this is the right long term solution.

But I agree, 10 is too small.  I'll run some timing experiments and maybe we can change the current settings from 1000/10 to 300/100 or so without slowing things down too much.
