### PR TITLE
Fix bug in OrderedRVIterator and PruneDeadFields

### LINKED ISSUE #3998: OrderedRVD assertion error
```
gnomad_ht = hl.read_table('gs://gnomad/variant_qc/temp/gnomad_genomes_annotations.ht')
ht = hl.read_table('gs://gnomad/annotations/hail-0.2/mt/genomes/rf/71afc169/gnomad.genomes.71afc169.rf_result.ht')
ht = ht.annotate(**gnomad_ht[ht.key])
ht.write(f'gs://gnomad-tmp/gnomad_{data_type}_rf_{run_hash}.ht', overwrite=True)
```

### PR DESCRIPTION
**Pull request by tpoterba**
fixes #3998

### CODE REVIEW

File: src/main/scala/is/hail/expr/ir/PruneDeadFields.scala [hunk 1]
```diff
@@ -240,7 +240,7 @@ object PruneDeadFields {
             else
               requestedType.rowType.fieldOption(x.rightFieldMapping(f.name)).map(reqF => f.name -> reqF.typ)
           }: _*),
-          globalType = minimal(requestedType.globalType))
+          globalType = minimal(right.typ.globalType))
```
Comment (tpoterba) [inline src/main/scala/is/hail/expr/ir/PruneDeadFields.scala]: unrelated bug. Not _technically_ a bug in master given that we don't support required top-level structs, but since previous builds were generating required empty global structs we got errors.

File: src/main/scala/is/hail/annotations/OrderedRVIterator.scala [hunk 2]
```diff
@@ -13,10 +13,10 @@ case class OrderedRVIterator(
 
   def restrictToPKInterval(interval: Interval): Iterator[RegionValue] = {
     val ur = new UnsafeRow(t.rowType)
-    val pk = new KeyedRow(ur, t.kRowFieldIdx)
+    val pk = new KeyedRow(ur, t.pkRowFieldIdx)
     iterator.filter { rv => {
       ur.set(rv)
-      val keep = interval.contains(t.kType.ordering, pk)
+      val keep = interval.contains(t.pkType.ordering, pk)
```
Comment (patrick-schultz) [inline src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: This makes me nervous. The previous version (using keys not partition keys) was definitely *correct*, and if it was doing something wrong, the bug is somewhere else. But given that I'll be changing all of this soon, if this is passing tests and fixes Laurent's problem, I guess it's fine.

Comment (tpoterba) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: This can't be correct as it is -- the partition range dependencies are constructed using the partition key, and then this is using the full key. One of the two is definitely wrong, because they're not consistent with each other

Comment (patrick-schultz) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: I think the right fix is probably to change the assertion in `OrderedRVD.apply` from `assert(partitionerBc.value.rangeBounds(i).contains(localType.pkType.ordering, pkUR))` to `assert(partitionerBc.value.rangeBounds(i).contains(localType.kType.ordering, kUR))`. That's what I have in my branch. But it's possible that has other bad interactions with other parts of the code still stuck in PK world. Would you mind giving it a try before we go with this?

Comment (tpoterba) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: sure

Comment (patrick-schultz) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: > This can't be correct as it is -- the partition range dependencies are constructed using the partition key, and then this is using the full key. One of the two is definitely wrong, because they're not consistent with each other

They're not actually inconsistent, because the partition key is a prefix of the key. `t.kType.ordering` will compare any two rows of any prefix of the key type correctly, so subsumes `t.pkType.ordering`. And the partition ranges are in general allowed to be any prefix of the key, independently of the partition key. What your change does is makes it effectively truncate the partition bounds to the partition key, but not in the correct way (it doesn't know anything about endpoint inclusivity).

Comment (tpoterba) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: I made assumptions about the guarantees of the larger system from those assertions -- if the assertions are wrong, that changes things!

Comment (tpoterba) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: in particular, that means that in the current master, the 'partition key' is not really a partition key, because `getPartitionPK()` and `getPartitionK` **do not** need to return the same partition

Comment (tpoterba) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: I don't care too much if this is getting fixed soon

Comment (tpoterba) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: made the change

Comment (tpoterba) [reply src/main/scala/is/hail/annotations/OrderedRVIterator.scala]: (still works)
