### PR TITLE
Fixed #1447

### LINKED ISSUE #1447: Unable to create HailContext in Scala spark-shell
I did the following 
```
import is.hail._
val hc = HailContext(sc)
```

When I did so, I got this error message 

```
java.util.NoSuchElementException: spark.hadoop.io.compression.codecs
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:235)
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:235)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.SparkConf.get(SparkConf.scala:235)
  at is.hail.HailContext$.checkSparkConfiguration(HailContext.scala:94)
  at is.hail.HailContext$.apply(HailContext.scala:171)
  ... 50 elided
```

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

File: src/main/scala/is/hail/HailContext.scala [hunk 1]
```diff
@@ -90,23 +90,14 @@ object HailContext {
...
     val problems = new ArrayBuffer[String]
 
-    val codecKey = "spark.hadoop.io.compression.codecs"
-    val codecs = conf.get(codecKey).split(",").toSet
-    val requiredCodecs = List("org.apache.hadoop.io.compress.DefaultCodec",
-      "is.hail.io.compress.BGzipCodec",
-      "org.apache.hadoop.io.compress.GzipCodec")
-    requiredCodecs.foreach { codec =>
-      if (!codecs.contains(codec))
-        problems += s"Invalid config parameter '$codecKey': missing codec '$codec'"
```
Comment (cseed) [inline src/main/scala/is/hail/HailContext.scala]: You don't want to check anymore?

Comment (tpoterba) [inline src/main/scala/is/hail/HailContext.scala]: we set these ourselves below.  They're hadoop conf parameters

Comment (cseed) [inline src/main/scala/is/hail/HailContext.scala]: Ah!   Got it.
