### PR TITLE
Add HWE Genotype Aggregator, fixes bug in imputesex, and fixes tutorial

### LINKED ISSUE #890: Calculate HWE from Aggregable[Genotype]
Want to do this:
hwe(gs.filter(g => g.sa.pheno == "case"))

Rather than this:
hwe(gs.filter(g => g.sa.pheno == "case" && g.isHomRef).count().toInt,
gs.filter(g => g.sa.pheno == "case" && g.isHet).count().toInt,
gs.filter(g => g.sa.pheno == "case" && g.isHomVar).count().toInt)

### PR DESCRIPTION
**Pull request by jigold**
- resolves #890
 - corrects schema type in imputesex (should be Long instead of Int)
 - fixed tutorial commands and output

### CODE REVIEW

**Comment by jigold** [comment]
Moved impute sex fix to new pull request

File: src/main/scala/org/broadinstitute/hail/expr/AST.scala [hunk 1]
```diff
@@ -884,6 +884,18 @@ case class ApplyMethod(posn: Position, lhs: AST, method: String, args: Array[AST
...
 
+      case (agg: TAggregable, "hwe", rhs) =>
+        if (rhs.nonEmpty)
+          parseError(s"""method `$method' does not take arguments""")
+        `type` = agg.elementType match {
+          case TGenotype => HWECombiner.signature
+          case _ => parseError(
+            s"""method `$method' can not operate on `$agg'
+                |  Accepted aggregable type: `Aggregable[Genotype]'
+             """.stripMargin
```
Comment (tpoterba) [inline src/main/scala/org/broadinstitute/hail/expr/AST.scala]: move up to the previous line (this puts an extra newline)
