### PR TITLE
[qob] cancel stage if any partitions fail.

### LINKED ISSUE #14597: [qob] Query on Batch worker stages should fail fast
### What happened?

Currently, Query on Batch waits for the full stage of workers to complete before collecting the results even in the event of a failure. Now that Query on Batch uses Job Groups, we can use the job group `cancel_after_n_failures` functionality to cancel remaining jobs in the stage after a certain number have failed.

Query on Batch should set `cancel_after_n_failures = 1` so that the user can see the error of the failed partition without waiting for all the partitions to run (and paying for them).

### Version

0.2.131

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by grohli**
## Change Description

Fixes #14597

cancel_after_n_failures = 1; cancels whole job group if one partition fails.

## Security Assessment

- This change has no security impact

### Impact Description

Unit tests and no interaction on anything secure.

(Reviewers: please confirm the security impact before approving)

### CODE REVIEW

**Comment by grohli** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/hail-is/hail/14747?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#14747** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14747?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#14684** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14684?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#14686](https://github.com/hail-is/hail/pull/14686) <a href="https://app.graphite.dev/github/pr/hail-is/hail/14686?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#14683** <a href="https://app.graphite.dev/github/pr/hail-is/hail/14683?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @grohli and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by chrisvittal — APPROVED** [review]
Thanks for the enhancement!

File: hail/src/test/scala/is/hail/services/BatchClientSuite.scala [hunk 1]
```diff
@@ -46,6 +47,38 @@ class BatchClientSuite extends TestNGSuite {
...
+        batch_id = batchId,
+        absolute_parent_id = parentJobGroupId,
+        cancel_after_n_failures = Some(1),
+        token = tokenUrlSafe,
+        jobs = FastSeq(
+          JobRequest(
+            always_run = false,
+            process = BashJob(
+              image = "ubuntu:22.04",
+              command = Array("/bin/bash", "-c", "sleep 1d"),
```
Comment (patrick-schultz) [inline hail/src/test/scala/is/hail/services/BatchClientSuite.scala:63]: I wonder if we should make the sleep duration smaller, like 30m or 1h, so that if for some reason the `cancel_after_n_failures` feature stops working, the test won't take a day to fail. But I'm not sure where the line is where the test becomes flakey if we make it too short.

File: hail/src/main/scala/is/hail/services/BatchClient.scala [hunk 2]
```diff
@@ -252,6 +255,9 @@ case class BatchClient private (req: Requester) extends Logging with AutoCloseab
         JObject(
           "job_group_id" -> JInt(1), // job group id relative to the update
           "absolute_parent_id" -> JInt(jobGroup.absolute_parent_id),
+          "cancel_after_n_failures" -> jobGroup.cancel_after_n_failures.map(JInt(_)).getOrElse(
+            JNull
+          ),
```
Comment (ehigham) [inline hail/src/main/scala/is/hail/services/BatchClient.scala:260]: thinking about this, `.getOrElse(JNull)` may be unnecessary - you can probably delete it

Comment (ehigham) [reply hail/src/main/scala/is/hail/services/BatchClient.scala:260]: This wont work unless you call `decompose` on the option - ignore the above.

**Comment by grohli** [comment]
Just revisiting this comment--does the question you had about the test still apply? Or is it several commits old now?

**Comment by grohli** [comment]
> Thanks Greg, looks great! Just one question about the test.

Just revisiting this comment--does the question you had about the test still apply? Or is it several commits old now?

**Review by patrick-schultz — APPROVED** [review]
Thanks Greg! Looks like you already addressed my question about the test by shortening the sleep to 5 min.
