### PR TITLE
Jg filesort

### LINKED ISSUE #814: copyMerge doesn't scale past 100k partitions
globAndSort calls standard string comparison.  This will produce incorrectly ordered files when nPartitions >= 100k

```
 in copyMerge:
    val srcFileStatuses = srcFilenames.flatMap(f => globAndSort(f))

  def globAndSort(filename: String): Array[FileStatus] = {
    val fs = fileSystem(filename)
    val path = new hadoop.fs.Path(filename)

    val files = fs.globStatus(path)
    if (files == null)
      return Array.empty[FileStatus]

    files.sortWith(_.compareTo(_) < 0)
  }
```

### PR DESCRIPTION
**Pull request by jigold**
Resolves #814

### CODE REVIEW

**Comment by tpoterba** [comment]
I think the reason why it's failing is that globAndSort is using the parquet file getPartNumber, but should use the one for files created by rdd.saveAsTextFile

File: src/main/scala/org/broadinstitute/hail/utils/richUtils/RichHadoopConfiguration.scala [hunk 1]
```diff
@@ -108,15 +108,15 @@ class RichHadoopConfiguration(val hConf: hadoop.conf.Configuration) extends AnyV
...
-
     val destPath = new hadoop.fs.Path(destFilename)
     val destFS = fileSystem(destFilename)
 
     val codecFactory = new CompressionCodecFactory(hConf)
     val codec = Option(codecFactory.getCodec(new hadoop.fs.Path(destFilename)))
     val isBGzip = codec.exists(_.isInstanceOf[BGzipCodec])
 
-    val srcFileStatuses = srcFilenames.flatMap(f => globAndSort(f))
+    val srcFileStatuses = srcFilenames.flatMap(f => glob(f))
```
Comment (tpoterba) [inline src/main/scala/org/broadinstitute/hail/utils/richUtils/RichHadoopConfiguration.scala]: don't glob here, I think.  We've agreed to lift the glob/sort behavior out of copyMerge

File: src/main/scala/org/broadinstitute/hail/utils/richUtils/RichRDD.scala [hunk 2]
```diff
@@ -38,9 +38,11 @@ class RichRDD[T](val r: RDD[T]) extends AnyVal {
       case None => r.saveAsTextFile(tmpFileName)
     }
 
+    val partFileNames = hConf.globAll(Array(tmpFileName + "/part-*")).sortBy(f => getPartNumber(f))
```
Comment (tpoterba) [inline src/main/scala/org/broadinstitute/hail/utils/richUtils/RichRDD.scala]: can use the `glob` function instead of `globAll`
