### PR TITLE
Fix #5174 - LocusInterval length == 0

### LINKED ISSUE #5174: liftover error
FatalError: IllegalArgumentException: Zero-length interval cannot be lifted over.  Interval: null

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 20 times, most recent failure: Lost task 0.19 in stage 2.0 (TID 21, ap01-sw-wdp1.c.topmed-kathiresan-lipids-wgs.internal, executor 7): java.lang.IllegalArgumentException: Zero-length interval cannot be lifted over.  Interval: null
    at htsjdk.samtools.liftover.LiftOver.liftOver(LiftOver.java:137)
    at is.hail.io.reference.LiftOver.queryInterval(LiftOver.scala:61)
    at is.hail.variant.ReferenceGenome.liftoverLocusInterval(ReferenceGenome.scala:435)
    at is.hail.codegen.generated.C11.method1(Unknown Source)
    at is.hail.codegen.generated.C11.apply(Unknown Source)
    at is.hail.codegen.generated.C11.apply(Unknown Source)
    at is.hail.expr.ir.TableMapRows$$anonfun$21$$anonfun$apply$11.apply(TableIR.scala:627)
    at is.hail.expr.ir.TableMapRows$$anonfun$21$$anonfun$apply$11.apply(TableIR.scala:626)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.next(RVD.scala:1264)
    at is.hail.rvd.RVD$$anonfun$apply$25$$anon$3.next(RVD.scala:1258)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
    at scala.collection.Iterator$JoinIterator.next(Iterator.scala:232)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1138)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1137)
    at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1371)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1145)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1125)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:108)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by jigold**
@patrick-schultz I fixed this for the case of locus intervals, but wasn't sure if there was a reason we don't add the `isValid` check to the Interval constructors.

### CODE REVIEW

File: hail/src/main/scala/is/hail/variant/ReferenceGenome.scala [hunk 1]
```diff
@@ -240,6 +240,12 @@ case class ReferenceGenome(name: String, contigs: Array[String], lengths: Map[St
       else
         fatal(s"Invalid interval `$i' found. End `$end' is not within the range [1-${ contigLength(end.contig) }] for reference genome `$name'.")
     }
+
+    if (!Interval.isValid(locusType.ordering, start, end, includesStart, includesEnd))
```
Comment (tpoterba) [inline hail/src/main/scala/is/hail/variant/ReferenceGenome.scala]: I feel like this check should be on the interval constructor in the IR, then we will check this potential bug for generic intervals

Comment (patrick-schultz) [reply hail/src/main/scala/is/hail/variant/ReferenceGenome.scala]: I don't know why the check wasn't on interval constructors either. Maybe because the previous interval semantics allowed degenerate intervals, I was being extra cautious of making semantics changes.

**Comment by jigold** [comment]
@catoverdrive At some point, could you please help me figure out what the right way to fix this in the IntervalFunctions file is? I think I need to add a new method call to Interval.isValid and somehow check this in the Interval constructor function. Not urgent.

**Comment by jigold** [comment]
Going to make an issue to fix the more general problem with interval constructors not checking their inputs. This PR will just fix it here for now.
