### PR TITLE
[hail][bugfix] always truncate partitioner keys in TableMultiWayZipJoin

### LINKED ISSUE #8027: Fix multi_way_zip_join key issue
This pipeline:
```python3
# cwd = repo_root/hail
vcf2 = hl.import_vcf('src/test/resources/gvcfs/HG00268.g.vcf.gz', force_bgz=True, reference_genome='GRCh38')
vcf1 = hl.import_vcf('src/test/resources/gvcfs/HG00096.g.vcf.gz', force_bgz=True, reference_genome='GRCh38')
vcfs = [vcf1.rows().key_by('locus'), vcf2.rows().key_by('locus')]
ht = hl.Table.multi_way_zip_join(vcfs, 'data', 'new_globals')
ht._force_count()
```
Fails with:
```
java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:224)
        at is.hail.rvd.RVD.<init>(RVD.scala:46)
        at is.hail.rvd.RVD$.apply(RVD.scala:1411)
        at is.hail.expr.ir.TableMultiWayZipJoin.execute(TableIR.scala:925)
```

### PR DESCRIPTION
**Pull request by chrisvittal**
fixes #8027

cc @konradjk

### CODE REVIEW

**Comment by konradjk** [comment]
Can confirms this fixes my issue

File: hail/src/main/scala/is/hail/expr/ir/TableIR.scala [hunk 1]
```diff
@@ -882,7 +882,7 @@ case class TableMultiWayZipJoin(children: IndexedSeq[TableIR], fieldName: String
         info("TableMultiWayZipJoin: repartitioning children")
         val childRanges = childRVDs.flatMap(_.partitioner.rangeBounds)
         val newPartitioner = RVDPartitioner.generate(childRVDs.head.typ.kType.virtualType, childRanges)
-        childRVDs.map(_.repartition(newPartitioner, ctx))
+        childRVDs.map(_.repartition(newPartitioner, ctx).truncateKey(typ.key.length))
```
Comment (patrick-schultz) [inline hail/src/main/scala/is/hail/expr/ir/TableIR.scala]: Ah, I see the problem. But you're computing a new common partitioner with the wrong key, repartitioning each child RVD, then fixing up the partitioner on each child RVD. Better to just compute the right partitioner before doing the repartitioning. I think this should work:
```
val childRanges = childRVDs.flatMap(_.partitioner.coarsenedRangeBounds(typ.key.length))
val newPartitioner = RVDPartitioner.generate(typ.kType, childRanges)
childRVDs.map(_.repartition(newPartitioner, ctx))
```
