### PR TITLE
[hail][bugfix] make sure to lower children of BlockMatrixIR

### LINKED ISSUE #6197: LowerMatrixIR.lower is wrong for BlockMatrixIR
This code:
```scala
  private[this] def lower(bir: BaseIR): BaseIR = bir match {
    case ir: IR => lower(ir)
    case tir: TableIR => lower(tir)
    case mir: MatrixIR => lower(mir)
    case bmir: BlockMatrixIR => bmir
  }
```

needs to recur into BMIRs. If there is a MatrixIR inside a BMIR at all, it's not going to get lowered, and will cause a crash.

### PR DESCRIPTION
**Pull request by daniel-goldstein**
resolves #6197

### CODE REVIEW

File: hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala [hunk 1]
```diff
@@ -572,8 +572,15 @@ object LowerMatrixIR {
...
 
-    if (lowered.typ != tir.typ)
-      fatal(s"lowering changed type:\n  before: ${ tir.typ }\n  after: ${ lowered.typ }")
+    assertTypeUnchanged(tir, lowered)
+    lowered
+  }
+
+  private[this] def lower(bmir: BlockMatrixIR, ab: ArrayBuilder[(String, IR)]): BlockMatrixIR = {
+    val lowered = bmir match {
+      case noMatrixChildren => lowerChildren(noMatrixChildren, ab).asInstanceOf[BlockMatrixIR]
```
Comment (tpoterba) [inline hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala]: this is a trivial match statement. Just `val lowered = lowerChildren(bmir, ab)...`?

Comment (daniel-goldstein) [reply hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala]: Ya I thought it looked more consistent with the other lowerings and showed there just weren’t yet `BlockMatrixIR` that required a special pass. Happy to get rid of it if you want

Comment (tpoterba) [reply hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala]: ok, sure.
