### PR TITLE
[query] `HailContext` is not required in batch

### LINKED ISSUE #15072: QoB: A QoB driver job can fail because a HailContext already exists
Reported in https://hail.zulipchat.com/#narrow/channel/223457-Hail-Batch-support/topic/Error.20in.20QoB/with/539119133. Potential fixes discussed in https://hail.zulipchat.com/#narrow/channel/300487-Hail-Batch-Dev/topic/QoB.20JVM.20Job/with/539119265.

This bug appears to have been introduced by #14698. Before that, the driver job used this logic to ensure a HailContext was created:
```
    if (HailContext.isInitialized) {
      HailContext.get.backend = backend
      log.info("Default references added to already initialized HailContexet.")
    } else {
      HailContext(backend, 50, 3)
      log.info("HailContexet initialized.")
    }
```
This was changed to unconditionally attempt to create a HailContext.

### PR DESCRIPTION
**Pull request by ehigham**
Removes creation of a `HailContext` for QoB.  `HailContext.apply` previously registered a dense matrix operation. For compatibility, this has been moved to a `lazy val` in the newly added `linalg` package object (so that it's registered at most once). Each backend initialises that `lazy val` in a similar way to the `StreamReadConstraints` business.

This change cannot impact the Hail Batch instance as deployed by Broad Institute in GCP

Fixes #15072

### CODE REVIEW

File: hail/hail/src/is/hail/backend/driver/BatchQueryDriver.scala [hunk 1]
```diff
@@ -210,7 +208,6 @@ object BatchQueryDriver extends HttpLikeRpc with Logging {
         )
       )
     finally {
-      HailContext.stop()
```
Comment (patrick-schultz) [inline hail/hail/src/is/hail/backend/driver/BatchQueryDriver.scala:213]: This was calling `IRFunctionRegistry.clearUserFunctions()`. Is that still needed?
