### PR TITLE
Fix escaping of some edge identifiers like '$'

### LINKED ISSUE #5119: import_table gives bad error message if a column has a $
### Hail version:
reported on Jan 11 9:45 by @nikbaya on [zulip](https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/import_table.20IncompleteParseError)

`00f9b64d8`
### What you did:

```
import hail as hl
phesant_still_more1 = hl.import_table('gs://ukb31063-mega-gwas/phenotype-files/still-more-phesant/neale_lab_parsed_and_restricted_to_QCed_samples_cat_variables_both_sexes.1.tsv',
                                      missing='',impute=True,types={'all_sexes$userId':hl.tstr}).rename({'all_sexes$userId':'s'})
```
### What went wrong (all error messages here, including the full java stack trace):

```
---------------------------------------------------------------------------
IncompleteParseError                      Traceback (most recent call last)
<ipython-input-2-ebe253e83367> in <module>()
      1 phesant_still_more1 = hl.import_table('gs://ukb31063-mega-gwas/phenotype-files/still-more-phesant/neale_lab_parsed_and_restricted_to_QCed_samples_cat_variables_both_sexes.1.tsv',
----> 2                                       missing='',impute=True,types={'all_sexes$userId':hl.tstr}).rename({'all_sexes$userId':'s'})
      3 # phesant_still_more2 = hl.import_table('gs://ukb31063-mega-gwas/phenotype-files/still-more-phesant/neale_lab_parsed_and_restricted_to_QCed_samples_cat_variables_both_sexes.2.tsv',
      4 #                                       missing='',impute=True,types={'all_sexes$userId':hl.tstr})

<decorator-gen-1108> in import_table(paths, key, min_partitions, impute, no_header, comment, delimiter, missing, types, quote, skip_blank_lines, force_bgz)

/home/hail/hail.zip/hail/typecheck/check.py in wrapper(__original_func, *args, **kwargs)
    558     def wrapper(__original_func, *args, **kwargs):
    559         args_, kwargs_ = check_all(__original_func, args, kwargs, checkers, is_method=is_method)
--> 560         return __original_func(*args_, **kwargs_)
    561
    562     return wrapper

/home/hail/hail.zip/hail/methods/impex.py in import_table(paths, key, min_partitions, impute, no_header, comment, delimiter, missing, types, quote, skip_blank_lines, force_bgz)
   1327                                    delimiter, missing, no_header, impute, quote,
   1328                                    skip_blank_lines, force_bgz)
-> 1329     return Table._from_java(jt)
   1330
   1331

/home/hail/hail.zip/hail/table.py in _from_java(jt)
    319     @staticmethod
    320     def _from_java(jt):
--> 321         return Table(JavaTable(jt.tir()))
    322
    323     def __init__(self, tir):

/home/hail/hail.zip/hail/table.py in __init__(self, tir)
    328             Env.hc()._jhc, Env.hc()._backend._to_java_ir(self._tir))
    329
--> 330         self._type = self._tir.typ
    331
    332         self._row_axis = 'row'

/home/hail/hail.zip/hail/ir/base_ir.py in typ(self)
     78     def typ(self):
     79         jtir = Env.hc()._backend._to_java_ir(self)
---> 80         return ttable._from_java(jtir.typ())
     81
     82     def parse(self, code, ref_map={}, ir_map={}):

/home/hail/hail.zip/hail/expr/table_type.py in _from_java(jtt)
      9         return ttable(
     10             dtype(jtt.globalType().toString()),
---> 11             dtype(jtt.rowType().toString()),
     12             jiterable_to_list(jtt.key()))
     13

/home/hail/hail.zip/hail/expr/types.py in dtype(type_str)
    103     :class:`.HailType`
    104     """
--> 105     tree = type_grammar.parse(type_str)
    106     return type_node_visitor.visit(tree)
    107

/opt/conda/lib/python3.6/site-packages/parsimonious/grammar.py in parse(self, text, pos)
    113         """
    114         self._check_default_rule()
--> 115         return self.default_rule.parse(text, pos=pos)
    116
    117     def match(self, text, pos=0):

/opt/conda/lib/python3.6/site-packages/parsimonious/expressions.py in parse(self, text, pos)
    120         node = self.match(text, pos=pos)
    121         if node.end < len(text):
--> 122             raise IncompleteParseError(text, node.end, self)
    123         return node
    124

IncompleteParseError: Rule 'type' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with 'uct{all_sexes$userId' (line 1, column 4).
```

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #5119

### CODE REVIEW

File: hail/src/main/scala/is/hail/utils/package.scala [hunk 1]
```diff
@@ -215,7 +215,7 @@ package object utils extends Logging
     .filter(s => !s.isEmpty)
 
   def prettyIdentifier(str: String): String = {
-    if (str.matches("""\p{javaJavaIdentifierStart}\p{javaJavaIdentifierPart}*"""))
+    if (str.matches("""[_a-zA-Z]\w*"""))
```
Comment (tpoterba) [inline hail/src/main/scala/is/hail/utils/package.scala]: this is much more conservative. There is no reason to use the java identifier stuff if we don't have a good idea what's in it -- apparently "currency" characters are valid identifier starts!

File: hail/python/hail/utils/java.py [hunk 2]
```diff
@@ -178,7 +178,10 @@ def unescape_parsable(s):
 
 
 def escape_id(s):
-    return Env.jutils().escapeIdentifier(s)
+    if re.fullmatch(r'[_a-zA-Z]\w*', s):
```
Comment (tpoterba) [inline hail/python/hail/utils/java.py]: avoid some JVM trips

**Comment by tpoterba** [comment]
The rest of the stack does handle weird named fields, the problem was that this wasn't getting escaped correctly (well, that our python type parser had different assumptions about escaping than the string escaper).
