### PR TITLE
Better fam file error messages

### LINKED ISSUE #709: Better Fam file error reporting
When loading a plink binary file, if the delimiter is incorrect it currently fails with the following  cryptic error:

caught scala.MatchError: [Ljava.lang.String;@459f703f (of class [Ljava.lang.String;)

This was  a file with spaces (where the default is tab). As space seems to be the default for plink2, which was used to make these files, it may be worth allowing either by default.

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #709

### CODE REVIEW

File: src/main/scala/org/broadinstitute/hail/driver/ImportPlink.scala [hunk 1]
```diff
@@ -30,7 +30,7 @@ object ImportPlink extends Command {
 
     @Args4jOption(required = false, name = "-d", aliases = Array("--delimiter"),
       usage = ".fam file field delimiter regex")
-    var famDelimiter: String = "\\t"
+    var famDelimiter: String = "\\\\s+"
```
Comment (tpoterba) [inline src/main/scala/org/broadinstitute/hail/driver/ImportPlink.scala]: I think those are invalid for plink import.  I'd rather that be the special case than whitespace-delimited files

Comment (jbloom22) [inline src/main/scala/org/broadinstitute/hail/driver/ImportPlink.scala]: It looks like Plink 1.07 allows space or tab delimited, and Plink 1.9 is flexible while transitioning to Plink 2.00 which will be tab delimited.  I agree with Tim that IDs with spaces should not be allowed for Plink import:
https://www.cog-genomics.org/plink2/filter#indiv

Tim, I'd say just make sure there's a useful error message when an id does have a space.
