### PR TITLE
Fixes #705: if doesn't do numeric promotion

### LINKED ISSUE #705: if doesn't do numeric promotion
`if (c) 0 else 0.0` fails with: expected same type on then and else clause.

### PR DESCRIPTION
**Pull request by khernyo**
It also fixes numeric promotion of TInt to TLong, which threw an
assertion error before.

### CODE REVIEW

File: src/main/scala/org/broadinstitute/hail/expr/AST.scala [hunk 1]
```diff
@@ -1969,23 +1969,44 @@ case class SymRef(posn: Position, symbol: String) extends AST(posn) {
...
+        case TFloat  => value
+        case TLong   => valueType.asInstanceOf[TIntegral].makeLong(value)
+        case TInt    => value
+      }
+      def coerce(valueType: BaseType, value: Any): Any = valueType match {
+        case `ifType`    => value
+        case t: TNumeric => promoteNumeric(ifType.asInstanceOf[TNumeric], t, value)
+        case _           => value
+      }
+
```
Comment (tpoterba) [inline src/main/scala/org/broadinstitute/hail/expr/AST.scala]: I think this need not be so complicated -- we've faced this struggle elsewhere in the AST code, and now have some decent abstractions.  Something like this should work:

```scala
val coerce: (Any) => Any = `type` match { // type here is the result type of the AST node, which is the result of the if/then clause
  case t: TNumeric => (a: Any) => t.conv.to
  case _ => (a: Any) => a
}
```

We actually don't currently have the ability to do this exactly as I wrote it -- TNumeric doesn't have a NumericConversion member, so we'd have to match on Type again.  I think adding a `val conv: NumericConversion[_]` to the abstract `TNumeric` and its children would make this very elegant.  

Any thoughts?  Feel free to push back on this!

**Comment by khernyo** [comment]
This will still fail with a ClassCastException when evaluating the expression `"(if (true) 0 else 0.toFloat).toInt"`, but I'm not sure if it's deliberately not supported or just an oversight. Anyway, I think this would be fixed by #624

**Comment by tpoterba** [comment]
Hmm.  I'd think that Int + Float would be promoted to Double, is that not so?  Maybe we've got an issue somewhere else.  

I think putting that example in the expr test you added would be a great idea!

**Comment by khernyo** [comment]
It also fails on the expression `"[0, 0.toFloat][0].toInt"`. To fix it, a `makeFloat` method is needed in `TNumeric`. I'll fix it in a couple of days.

File: src/main/scala/org/broadinstitute/hail/expr/AST.scala (hunk 1 above)
Comment (khernyo) [inline src/main/scala/org/broadinstitute/hail/expr/AST.scala]: I'll try to simplify it.

**Comment by tpoterba** [comment]
Ah, good catch!  Yep, this is a bug in the current master.  That logic should be replaced with the conversions, and `makeDouble` and `makeLong` should go away.

**Comment by tpoterba** [comment]
Added issue #759 based on this conversation

**Comment by khernyo** [comment]
I just pushed the fix using TNumeric.conv

File: src/main/scala/org/broadinstitute/hail/expr/AST.scala [hunk 2]
```diff
@@ -1966,23 +1966,31 @@ case class SymRef(posn: Position, symbol: String) extends AST(posn) {
...
     val f1 = cond.eval(ec)
     val f2 = thenTree.eval(ec)
     val f3 = elseTree.eval(ec)
+
+    // this is necessary to avoid serializing `this` which is not serializable
+    // (and it would be an unnecessary leak anyway)
+    val ifType = `type`
+
     () => {
+      def coerce(value: Any): Any = ifType match {
```
Comment (cseed) [inline src/main/scala/org/broadinstitute/hail/expr/AST.scala]: `ifType` is invariant of the thunk, so you can lift the match out.  Something like:

```
  val coerce: (Any) => Any = `type`  match { ... }
  () => {
    val c = f()
    ...
```

Otherwise, looks great!

Comment (khernyo) [inline src/main/scala/org/broadinstitute/hail/expr/AST.scala]: You are right. I just pushed the fix. Let me know if it looks good so I can squash the commits together.

**Comment by tpoterba** [comment]
Looks great, thanks for contributing!
