### PR TITLE
[batch] Fix job_group cancellation logic in SQL procedures

### LINKED ISSUE #14864: Batch services fails to mark job started when the batch has more than one failed job group
### What happened?

The SQL procedure `mark_job_started` fails if a batch has more than one cancelled job group.

https://github.com/hail-is/hail/blob/8fe952b3f7ad85b5d61b97c1f8f51db02db091db/batch/sql/rename-job-groups-tables.sql#L717-L722

This has started happening more regularly after 61955dfbaf19cb916e157cf0ea34370c2e50e4cf, which added functionality to cancel the query's stage (job group) if one partition (job therein) failed.
I believe this bug is making workers seem stall doing nothing.

### Version

0.2.134

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/gear/csrf.py", line 27, in check_csrf_token
    return await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/gear/metrics.py", line 28, in monitor_endpoints_middleware
    response = await prom_async_time(REQUEST_TIME.labels(endpoint=endpoint, verb=verb), handler(request))  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/prometheus_async/aio/_decorators.py", line 55, in measure
    rv = await future
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_session/__init__.py", line 191, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/batch/driver/main.py", line 190, in wrapped
    return await fun(request, instance)
  File "/usr/local/lib/python3.9/dist-packages/batch/utils.py", line 45, in wrapped
    return await fun(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/batch/driver/main.py", line 399, in job_started
    return await asyncio.shield(job_started_1(request, instance))
  File "/usr/local/lib/python3.9/dist-packages/batch/driver/main.py", line 388, in job_started_1
    await mark_job_started(request.app, batch_id, job_id, attempt_id, instance, start_time, resources)
  File "/usr/local/lib/python3.9/dist-packages/batch/driver/job.py", line 295, in mark_job_started
    rv = await db.execute_and_fetchone(
  File "/usr/local/lib/python3.9/dist-packages/gear/database.py", line 55, in wrapper
    return await f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gear/database.py", line 325, in execute_and_fetchone
    return await tx.execute_and_fetchone(sql, args, query_name)
  File "/usr/local/lib/python3.9/dist-packages/gear/database.py", line 247, in execute_and_fetchone
    await cursor.execute(sql, args)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1172, 'Result consisted of more than one row')
```

### PR DESCRIPTION
**Pull request by ehigham**
The following sql triggers and procedures were not updated to reflect
changes to job cancellation when job groups merged: 
- `jobs_after_update`
- `cancel_batch`
- `schedule_job`
- `mark_job_creating`
- `mark_job_started` 

These error if there's more than 1 cancelled job group in the batch,
preventing jobs being marked complete even if they had been executed
sucessfully.

This change drops and re-creates these entities with updated job 
cancellation logic. 

Fixes #14864

## Security Assessment

This change impacts the Hail Batch instance as deployed by Broad Institute in GCP.
This change has a medium security impact, affecting
- the stored SQL procedures in the batch database, and
- error handling in the batch worker.

This change does not expose new functionality that could be exploited.

### Appsec Review

- [x] Required: The impact has been assessed and approved by appsec

### CODE REVIEW

File: batch/sql/11708-is-job-cancelled.sql [hunk 1]
```diff
@@ -0,0 +1,382 @@
+DELIMITER $$
```
Comment (ehigham) [inline batch/sql/11708-is-job-cancelled.sql:1]: Compare with https://github.com/hail-is/hail/blob/62efb32d9544b0c964019345281e89b235f02f92/batch/sql/finalize-job-groups.sql#L4

File: batch/sql/119-is-job-cancelled.sql
Comment (ehigham) [inline batch/sql/119-is-job-cancelled.sql:1]: Compare with
https://github.com/hail-is/hail/blob/62efb32d9544b0c964019345281e89b235f02f92/batch/sql/finalize-job-groups.sql
https://github.com/hail-is/hail/blob/62efb32d9544b0c964019345281e89b235f02f92/batch/sql/rename-job-groups-tables.sql

**Comment by ehigham** [comment]
Tested by submitting stress tests and monitoring batch-driver logs
for errors to batch services running in
- the default k8s namespace to reproduce the errors
- a dev deployment patched with this branch.

The stress test is below and requires https://github.com/hail-is/hail/pull/14817.

The default-namespace deployment logged errors matching that of #14864
whereas the patched instance did not. I claim that this change fixes that issue.

```python
from random import choice, random
from typing import Callable, Optional, TypeVar, Union

import hailtop.batch as hb


def flip(p):
    return random() <= p


A = TypeVar('A')


def prob(p: float, f: Callable[[], A]) -> Optional[A]:
    return f() if flip(p) else None


def job_group_name(a: Union[hb.Batch, hb.JobGroup]) -> str:
    return a.attributes['name'] if isinstance(a, hb.JobGroup) else ''


def job_group_tree(root: Union[hb.Batch, hb.JobGroup], depth: int, arity: int) -> hb.JobGroup:
    if depth <= 1:
        return

    failure_threashold = prob(0.5, lambda: 1)
    group_name = f'{job_group_name(root)}/{depth}'
    jg = root.create_job_group(attributes={'name': group_name}, cancel_after_n_failures=failure_threashold)
    j = jg.new_bash_job(name=f'({group_name}, 0)')
    j.command(f'sleep {choice(range(4))}; exit {1 if flip(0.1) else 0}')

    for m in range(arity):
        jm = jg.new_bash_job(name=f'({group_name}, {m + 1})')
        jm = jm.depends_on(j)
        jm.command(f'sleep {choice(range(4))}; exit {1 if flip(0.1) else 0}')
        jm._always_run = flip(0.1)

        if flip(0.01):
            jm._machine_type = 'n1-standard-1'
            jm.spot(flip(0.5))

    for n in range(arity):
        job_group_tree(jg, depth - 1, arity)


def stress():
    b = hb.Batch(name='stress', backend=hb.ServiceBackend(billing_project='ehigham-trial'))
    job_group_tree(b, depth=3, arity=100)
    b.run(open=False, wait=False)


if __name__ == "__main__":
    stress()
```

File: batch/sql/119-is-job-cancelled.sql
Comment (grohli) [reply batch/sql/119-is-job-cancelled.sql:1]: Is [this](https://github.com/hail-is/hail/blob/026bd7f1f5e011ef943fc1cfae2b685ab2af86ed/batch/sql/finalize-job-groups.sql#L303) the original `cancel_job_group`? (unless I missed it in those two places you linked, which is very likely)

File: batch/sql/119-is-job-cancelled.sql [hunk 2]
```diff
@@ -0,0 +1,521 @@
...
+  INNER JOIN job_groups_cancelled   AS c
+     ON self.batch_id    = c.id
+    AND self.ancestor_id = c.job_group_id
+  WHERE self.batch_id     = batch_id
+    AND self.job_group_id = job_group_id
+) $$
+
+
+DROP FUNCTION IF EXISTS is_job_cancelled $$
+CREATE FUNCTION is_job_cancelled (batch_id BIGINT, job_id INT)
```
Comment (grohli) [inline batch/sql/119-is-job-cancelled.sql:28]: It looks like this is replacing:
```SQL
  SELECT (jobs.cancelled OR job_groups_cancelled.id IS NOT NULL) AND NOT jobs.always_run
  INTO cur_job_cancel
  FROM jobs
  LEFT JOIN job_groups_cancelled ON job_groups_cancelled.id = jobs.batch_id
  WHERE batch_id = in_batch_id AND job_id = in_job_id
  LOCK IN SHARE MODE;
```
is that right? ~~Can I get a quick rundown on what the `job_group_self_and_ancestors` table looks like?~~ Just kidding I think I was able to figure it out.

Looks good, am I correct in saying this now does "check intersection of `job_group_self_and_ancestors` and `job_groups_cancelled`" instead of just "check `job_groups_cancelled`" to help figure out if a job is cancelled?

Comment (ehigham) [reply batch/sql/119-is-job-cancelled.sql:28]: Let's do a worked example.
If a job group is cancelled, all jobs and job groups contained therein are also cancelled.

`job_group_self_and_ancestors` describes the job group hierarchy.

Let's say we have some batch with 2 nested job groups, `p` and `q`.
The table looks like:
```
batch_id | job_group_id | ancestor_id | level 
---------+--------------+-------------+------
    n    |       0      |      0      |   0
    n    |       p      |      p      |   0
    n    |       p      |      0      |   1
    n    |       q      |      q      |   0
    n    |       q      |      p      |   1
    n    |       q      |      0      |   2
```
Now let's say job group `p` has been cancelled via the `cancel_after_max_failures` mechanism. The `job_groups_cancelled` table will have the record:
```
batch_id | job_group_id 
---------+--------------
    n    |       p     
```
By inner-joining `job_group_self_and_ancestors` (s) with `job_groups_cancelled` (c) on `s.ancestor_id = c.job_group_id`, we obtain the derived table (omitting batch_id):
```
s.job_group_id | s.ancestor_id | s.level | c.job_group_id
---------------+---------------+---------+---------------
      p        |       p       |    0    |      p
      q        |       p       |    1    |      p
```
Thus, we see the cancelled job groups in the batch:
- `p` because it itself is cancelled
- `q` because it has ancestor `p` that's been cancelled

File: batch/sql/119-is-job-cancelled.sql
Comment (ehigham) [reply batch/sql/119-is-job-cancelled.sql:1]: I believe so yes

File: batch/sql/119-is-job-cancelled.sql (hunk 2 above)
Comment (grohli) [reply batch/sql/119-is-job-cancelled.sql:28]: Amazing, thanks Ed, that was extremely clear
