### PR TITLE
Move entries array to end of rvRowType for MatrixUnionRows

### LINKED ISSUE #4527: Hail optimizer changes the type but does not show a difference in printable type
### Hail version:
`784ab2796878`
### What you did:
```
In [1]: import hail as hl
   ...: 
   ...: t1kg = hl.balding_nichols_model(3, 100, 100)
   ...: print(t1kg.describe())
   ...: t1kg = t1kg_sm.repartition(500) 
   ...: t1kg = t1kg._filter_partitions([1])
   ...: t1kg = hl.split_multi(t1kg)
   ...: t1kg._force_count_rows()
```
### What went wrong (all error messages here, including the full java stack trace):
```
FatalError: HailException: optimization changed type!
  before: Matrix{global:Struct{bn:Struct{n_populations:Int32,n_samples:Int32,n_variants:Int32,n_partitions:Int32,pop_dist:Array[Int32],fst:Array[Float64],mixture:Boolean}},col_key:[sample_idx],col:Struct{sample_idx:Int32,pop:Int32},row_key:[[locus,alleles]],row:Struct{locus:Locus(GRCh37),alleles:Array[String],ancestral_af:Float64,af:Array[Float64],a_index:Int32,was_split:Boolean,old_locus:Locus(GRCh37),old_alleles:Array[String]},entry:Struct{GT:Call}}
  after:  Matrix{global:Struct{bn:Struct{n_populations:Int32,n_samples:Int32,n_variants:Int32,n_partitions:Int32,pop_dist:Array[Int32],fst:Array[Float64],mixture:Boolean}},col_key:[sample_idx],col:Struct{sample_idx:Int32,pop:Int32},row_key:[[locus,alleles]],row:Struct{locus:Locus(GRCh37),alleles:Array[String],ancestral_af:Float64,af:Array[Float64],a_index:Int32,was_split:Boolean,old_locus:Locus(GRCh37),old_alleles:Array[String]},entry:Struct{GT:Call}}
```

### LINKED ISSUE #4761: MatrixUnionRows type requirements are narrower than MT.union_rows in Python
In Python, we check that the row.dtype and entry.dtype are the same for all MTs. In scala we assert that the RVDTypes are the same. This means that both requiredness and entry array location can cause problems.

### PR DESCRIPTION
**Pull request by chrisvittal**
Closes #4527
Closes #4761

This is a workaround to prevent issues with MatrixUnionRows when the
entries arrays are in different places in the rvRowType in each of the
children.  Furthermore, it prevents issues if the entries array is
pruned and then re-added later in rebuild, where it will often be
inserted, likely by MatrixMapRows, at the end of the rvRowType. This
rearrangement caused the type equality assertion in Optimize to fail.

### CODE REVIEW

File: hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala [hunk 1]
```diff
@@ -2084,9 +2084,20 @@ case class MatrixRepartition(child: MatrixIR, n: Int, shuffle: Boolean) extends
   override def columnCount: Option[Int] = child.columnCount
 }
 
-case class MatrixUnionRows(children: IndexedSeq[MatrixIR]) extends MatrixIR {
-
-  require(children.length > 1)
+case class MatrixUnionRows(unmappedChildren: IndexedSeq[MatrixIR]) extends MatrixIR {
+  require(unmappedChildren.length > 1)
+
+  val children = unmappedChildren.map { c =>
```
Comment (tpoterba) [inline hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala]: I don't like this - I don't think the `unmappedChildren` should be stored in the node. 

How about a static `MatrixUnionRows.unify(mts: IndexedSeq[MatrixIR]): MatrixUnionRows` that does the proper transformations?

This will also fix the failing test.

Comment (tpoterba) [reply hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala]: and unify should be called in the pruner as well.

**Comment by chrisvittal** [comment]
I'm not in an environment where I can easily run tests right now. Let's see what CI has to say about these changes.

File: hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala (hunk 1 above)
Comment (chrisvittal) [reply hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala]: I'm not sure that `unify` needs to be called in the pruner. I think it may only need to be called in `Interpret`. The tests pass when it's called in Interpret at least.

**Comment by chrisvittal** [comment]
I have a parallel branch that doesn't delete `unmappedChildren`, https://github.com/chrisvittal/hail/tree/issue-4527-2-working and I would be fine with merging either. The trick there was to actually memoize `children` rather than `unmappedChildren`

File: hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala [hunk 2]
```diff
@@ -2084,13 +2084,30 @@ case class MatrixRepartition(child: MatrixIR, n: Int, shuffle: Boolean) extends
...
+  }
 
+  def unify(mirs: IndexedSeq[MatrixIR]): IndexedSeq[MatrixIR] = mirs.map(fixup)
+}
+
+case class MatrixUnionRows(children: IndexedSeq[MatrixIR]) extends MatrixIR {
   require(children.length > 1)
 
-  val typ: MatrixType = children.head.typ
+  val typ = MatrixUnionRows.fixup(children.head).typ
```
[the remark this answers is not in the document]
Comment (chrisvittal) [reply hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala]: I also don't like it, but we need to get the types right.
