### PR TITLE
Fix bug in TableLeftJoinRightDistinct related to RVD physical key

### LINKED ISSUE #5289: Fix RVD key bug
https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/AssertionError

### PR DESCRIPTION
**Pull request by tpoterba**
Fixes #5289

### CODE REVIEW

File: hail/src/main/scala/is/hail/expr/ir/TableIR.scala [hunk 1]
```diff
@@ -642,10 +642,12 @@ case class TableLeftJoinRightDistinct(left: TableIR, right: TableIR, root: Strin
     val leftValue = left.execute(hc)
     val rightValue = right.execute(hc)
 
+    val joinKey = left.typ.key.length
+    assert(joinKey == right.typ.key.length)
```
Comment (chrisvittal) [inline hail/src/main/scala/is/hail/expr/ir/TableIR.scala]: If we're going to require equality here, shouldn't we just require equality in the class in general?

Comment (tpoterba) [reply hail/src/main/scala/is/hail/expr/ir/TableIR.scala]: ah, this is wrong. pushing up a fix.
