### PR TITLE
[query] fix job group state polling

### LINKED ISSUE #15118: [query] query driver polls cancelled job group indefinitely
### What happened?

The query driver polls for job groups to complete by looking at the `complete` bool field in the job group json response. [1]

When a job group is cancelled in the UI, susequent responses from batch indicate the job group has been cancelled but may not be complete.

Thus, the driver continutes to poll for status changes.

[1] https://github.com/hail-is/hail/blob/4ea45dc1c7e7fc8ec8654cd7d7a381e02f703ebf/hail/hail/src/is/hail/services/BatchClient.scala#L306-L313

### Version

0.2.135

### Relevant log output

```shell
$ hailctl curl default batch '/api/v1alpha/batches/8317529/job-groups/88' | jq
{
  "batch_id": 8317529,
  "job_group_id": 87,
  "state": "cancelled",
  "complete": false,
  "n_jobs": 3347,
  "n_completed": 76,
  "n_succeeded": 76,
  "n_failed": 0,
  "n_cancelled": 0,
```

### PR DESCRIPTION
**Pull request by ehigham**
Fixes #15118  

This change cannot impact the Hail Batch instance as deployed by Broad Institute in GCP

### CODE REVIEW

File: hail/hail/src/is/hail/services/BatchClient.scala [hunk 1]
```diff
@@ -309,8 +309,7 @@ case class BatchClient private (req: Requester) extends Logging with AutoCloseab
     while (true) {
       val jobGroup = getJobGroup(batchId, jobGroupId)
 
-      if (jobGroup.complete)
-        return jobGroup
+      if (jobGroup.state != JobGroupStates.Running) return jobGroup
```
Comment (cjllanwarne) [inline hail/hail/src/is/hail/services/BatchClient.scala]: Are these enumerated anywhere? Are we sure there's not a `Ready`?

Comment (cjllanwarne) [reply hail/hail/src/is/hail/services/BatchClient.scala]:
```
  case object Failure extends JobGroupState
  case object Cancelled extends JobGroupState
  case object Success extends JobGroupState
  case object Running extends JobGroupState
```

... yes

Comment (ehigham) [reply hail/hail/src/is/hail/services/BatchClient.scala]: These are reimplemented from batch/front_end.py. fwiw I don't like this solution and feels fragile.

**Review by chrisvittal — APPROVED** [review]
